# Generated by Django 5.0.4 on 2024-05-01 04:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_alter_shippingaddress_shipping_address2_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitems",
            options={"verbose_name_plural": "Order Items"},
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_address2",
        ),
    ]
