# Generated by Django 5.0.4 on 2024-05-02 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_alter_orderitems_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="shipping_address1",
            new_name="shipping_address",
        ),
    ]
