# Generated by Django 5.0.4 on 2024-05-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_rename_shipping_address1_order_shipping_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipped",
            field=models.BooleanField(default=False),
        ),
    ]
