# Generated by Django 5.0.6 on 2024-05-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_order_shipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_shipped",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
